import logging
import re
import sys
from collections.abc import Sequence
from pathlib import Path

logger = logging.getLogger(__name__)

PACKAGE_RE = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9_.-]*)(?:\[[^\]]*\])?\s*==\s*([^\s\\;]+)"
)


def parse(file: Path) -> list[str]:
    assert isinstance(file, Path), f"Expected Path, got <{type(file)}> {file}"
    if not file.exists():
        sys.exit(f"lockfile not found: {file}")

    if file.name == "Cargo.lock" or file.name.endswith(".cargo.lock"):
        return parse_crate(file)
    if (
        file.suffix in {".txt", ".pip", ".requirements", ".in"}
        or file.name.endswith(".txt.lock")
        or file.name.endswith(".pip.lock")
        or file.name.endswith(".requirements.lock")
        or file.name == "requirements.lock"
    ):
        return parse_pypi(file)
    if file.suffix == ".lock":
        content = file.read_text(encoding="utf-8", errors="replace")
        if (
            "# This file is automatically @generated by Cargo." in content
            or 'source = "registry+https://github.com/rust-lang/crates.io-index"'
            in content
        ):
            return parse_crate(file)
        return parse_pypi(file)

    sys.exit(f"Unsupported lockfile type: {file}")


def lines(text: str) -> Sequence[str]:
    """Yield logical lines, joining lines ending with a backslash and skipping comments."""
    accumulated: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if " #" in line:
            line = line.split(" #", 1)[0].strip()

        if line.endswith("\\"):
            accumulated.append(line[:-1].rstrip())
        else:
            if accumulated:
                accumulated.append(line)
                combined = " ".join(part for part in accumulated if part)
                accumulated.clear()
                if combined:
                    yield combined
            elif line:
                yield line
    if accumulated:
        combined = " ".join(part for part in accumulated if part)
        if combined:
            yield combined


def parse_pypi(file: Path) -> list[str]:
    deps: list[str] = []

    for line in lines(file.read_text(encoding="utf-8")):
        match = PACKAGE_RE.match(line)
        if match:
            name, version = match.group(1), match.group(2)
            deps.append(f"pypi/pypi/-/{name}/{version}")
        elif line.startswith("-"):
            logger.debug(f"Ignoring pip option line: {line}")
        else:
            logger.warning(f"Skipping unsupported pip requirement line: {line}")

    return deps


def parse_crate(file: Path):
    deps: list[str] = []

    assert isinstance(file, Path), f"Expected Path, got <{type(file)}> {file}"

    text = file.read_text(encoding="utf-8")

    # Split into [[package]] blocks and parse simple key=value lines into a dict.
    for block in text.split("[[package]]"):
        block = block.strip()
        if not block:
            continue

        fields: dict[str, str] = {}
        for line in block.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            fields[k.strip()] = v.strip().strip('"')

        name = fields.get("name")
        version = fields.get("version")
        source = fields.get("source")

        if not (name and version):
            continue

        # Only crates.io is supported today; detect via presence of 'crates' in source.
        if source and "crates" not in source.lower():
            raise ValueError(f"Unknown crate registry source: {source}")

        deps.append(f"crate/cratesio/-/{name}/{version}")

    return deps
